GRANT SELECT
ON dbsys13.FERIENWOHNUNG TO dbsys63;

GRANT SELECT
ON dbsys13.AUSSTATTUNG TO dbsys63;

GRANT SELECT
ON dbsys13.TOURIATTR TO dbsys63;

GRANT SELECT, UPDATE
ON dbsys13.ADRESSE TO dbsys63;

GRANT SELECT
ON dbsys13.LAND TO dbsys63;

GRANT SELECT, UPDATE, DELETE
ON dbsys13.KUNDE TO dbsys63;

GRANT SELECT, UPDATE
ON dbsys13.BUCHUNG TO dbsys63;

GRANT SELECT
ON dbsys13.RECHNUNG TO dbsys63;

GRANT SELECT, UPDATE
ON dbsys13.ANZAHLUNG TO dbsys63;

GRANT SELECT, INSERT, UPDATE, DELETE
ON dbsys13.BEWERTUNG TO dbsys63;

GRANT SELECT
ON dbsys13.FW_HAT_AUS TO dbsys63;

GRANT SELECT
ON dbsys13.LIEGTIMUMKREIS TO dbsys63;

commit;


